# Generated by Django 6.0.7 on 2026-08-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem_payment_method_cashregisterentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="cash_portion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("CASH", "Cash"), ("CARD", "Card"), ("MIXED", "Card + Cash")],
                max_length=5,
                null=True,
            ),
        ),
    ]
