# Generated by Django 6.0.7 on 2026-08-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="is_helper",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="table",
            name="label",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="table",
            name="location_note",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
