# Generated by Django 6.0.7 on 2026-07-14 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hr', models.CharField(max_length=120, verbose_name='Name (Croatian)')),
                ('name_en', models.CharField(max_length=120, verbose_name='Name (English)')),
                ('name_sq', models.CharField(max_length=120, verbose_name='Name (Albanian)')),
                ('group', models.CharField(choices=[('FOOD', 'Food'), ('DRINK', 'Drink')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['group', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hr', models.CharField(max_length=120, verbose_name='Name (Croatian)')),
                ('name_en', models.CharField(max_length=120, verbose_name='Name (English)')),
                ('name_sq', models.CharField(max_length=120, verbose_name='Name (Albanian)')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hr', models.CharField(max_length=120, verbose_name='Name (Croatian)')),
                ('name_en', models.CharField(max_length=120, verbose_name='Name (English)')),
                ('name_sq', models.CharField(max_length=120, verbose_name='Name (Albanian)')),
                ('variant_label', models.CharField(blank=True, max_length=60, verbose_name='Variant (e.g. 0.33l, Velika porcija)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category')),
                ('modifier_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='menu.modifiergroup')),
            ],
            options={
                'ordering': ['category', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ModifierOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hr', models.CharField(max_length=120, verbose_name='Name (Croatian)')),
                ('name_en', models.CharField(max_length=120, verbose_name='Name (English)')),
                ('name_sq', models.CharField(max_length=120, verbose_name='Name (Albanian)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.modifiergroup')),
            ],
            options={
                'ordering': ['group', 'order', 'id'],
            },
        ),
    ]
